### ISSUE TITLE
RedisBungeeAPI is null

### ISSUE THREAD

**Issue by njb-said** [thechunknetwork/RedisBungee#15]
It appears that the RedisBungee.getApi() is returning null. (Running latest version from Spigot resources)
Log output:
```
11:34:18 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"54c9ade":1032
11:34:18 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
11:34:18 [INFO] Loaded plugin RedisBungee version 0.3.4 by tuxed
11:34:18 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"54c9ade":1032 by SpigotMC
11:34:18 [INFO] Loaded plugin Bongee version 1.0.0 by null
11:34:18 [INFO] [RedisBungee] Successfully connected to Redis.
11:34:18 [INFO] Enabled plugin RedisBungee version 0.3.4 by tuxed
11:34:18 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"54c9ade":1032 by SpigotMC
11:34:18 [INFO] Enabled plugin Bongee version 1.0.0 by null
11:34:18 [INFO] Listening on /0.0.0.0:25568
11:34:19 [INFO] §aCreated Mongo instance
11:34:19 [INFO] §aFound 8 servers
11:34:19 [INFO] §aDetected 2 servers as hub.
```
As you can see it connects to Redis fine, but whenever I do RedisBungee.getApi() it returns null
I have also tried using the latest Jenkins build, but still not working.

**Comment by vemacs** [comment]
Is RedisBungee a dependency in your plugin's `bungee.yml/plugin.yml`?

**Comment by njb-said** [comment]
It is a dependency

**Comment by minecrafter** [comment]
Can you try the latest CI build?

**Comment by njb-said** [comment]
As a plugin? or as a dependency?

**Comment by minecrafter** [comment]
Plugin

**Comment by njb-said** [comment]
Nope, still didn't work

**Comment by minecrafter** [comment]
Try running any RedisBungee command that queries something (`/glist` should suffice). Does it work?

**Comment by njb-said** [comment]
I have that disabled, I did do /serverid and /serverids which work fine

**Comment by minecrafter** [comment]
In that case, I am not sure where you're going with this. Since you indicated that `/serverid` and `/serverids` work, it's no longer RedisBungee's fault by this point.
