### ISSUE TITLE
Issue while updating to 0.3.6 : unexpected NPE

### ISSUE THREAD

**Issue by alphartdev** [thechunknetwork/RedisBungee#22]
Hi Tux,
some of my users started to have errors after updating to 0.3.6, so I investigated and managed to replicate bugs on my side. There may be several, but for now I just reproduced one : 
The bug reported was an NPE at line 105 of BAT in the Lookup formatter (https://github.com/alphartdev/BungeeAdminTools/blob/master/src/main/java/fr/Alphart/BAT/Modules/Core/LookupFormatter.java#L105).
You'll see that before this line of code there was a condition : `if the player whose UUID is pUUID is online, then` so that means that if the line 105 is reached this player is online. Then I checked which variable was null and it appears that this code `RedisBungee.getApi().getServerFor(pUUID)` returned null, which then triggered an NPE  as I was trying to call `getName()` on a null ServerInfo.
And that's the problem, the player is considered online (`isPlayerOnline(pUUID)`) but it doesn't have a server (`RedisBungee.getApi().getServerFor(pUUID) returns null`). 
Any ideas what might be causing that ?

**Comment by minecrafter** [comment]
This can actually be the case if the player is still logging in. Which circumstances lead to the issue?

**Comment by alphartdev** [comment]
The player I was testing with was fully connected to the bukkit server (i.e he saw the world, can modify it etc). It was working fine with previous RedisBungee version (under the same circumstaces).

**Comment by minecrafter** [comment]
I don't know what the issue is exactly, but my changes to `DataManager` should have not affected anything.

How often can you reproduce the issue? How can I reproduce the issue?

**Comment by minecrafter** [comment]
Can you reproduce the issue with RedisBungee's `/find` command as well?

**Comment by alphartdev** [comment]
I tried the /find which wasn't working but the /pproxy was, so I thought a bit and noticed that my servers in my two bungee didn't had the same name (but the same IPs). Once they had the same name, everything is working smoothly again.
Sorry for wasting your time, I'm going to see with my users if that was the same issue for them.

If it is then it's alright and thanks for your help, otherwise I'll to investigate more. In the meantime, could you not close this issue if the latter case happens? Thanks

**Comment by minecrafter** [comment]
There we go, glad you found the issue. Yes, RedisBungee expects a 1:1 mapping of the servers configured on each proxy.
